#
#-----------------------------
# JDK SETUP
#-----------------------------
#

- hosts: all
  sudo: yes
  roles:
    - jdk


#
#-----------------------------
# ZOOKEEPER CLUSTER SETUP
#-----------------------------
#

- hosts: zookeepernodes
  sudo: yes
  roles:
    - zookeeper_install_tarball

#
#-----------------------------
# STORM CLUSTER SETUP
#-----------------------------
#

- hosts: stormcluster
  sudo: yes
  roles:
    - storm_commons_tarball

- hosts: stormnimbusnodes
  sudo: yes
  roles:
    - storm_nimbus

- hosts: stormsupervisornodes
  sudo: yes
  roles:
    - storm_supervisor
